# Lecture 3 Playground

Run the included code blocks, understand the output, and note any questions you have!

Square brackets are used to enclose elements of a vector or matrix. Use spaces for horizontal concatenation and semicolons or newlines for vertical concatenation.

In [2]:
A = [ 1 2 3 4 5; 50 40 30 20 10
π sqrt(2) exp(1) (1+sqrt(5))/2 log(3) ]

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

The `size` function gives us the dimensions of an input array.

In [3]:
m,n = size(A)

(3, 5)

A vector is slightly different than a matrix.  A matrix has two dimensions, but a vector has only one dimension.  

In [4]:
x = [ 3, 3, 0, 1, 0 ]
size(x)

(5,)

As long as all blocks are size-compatible, we can build block matrices from vectors and matrices in Julia!

In [5]:
[ x x ]

5×2 Matrix{Int64}:
 3  3
 3  3
 0  0
 1  1
 0  0

In [6]:
[ x; x ]

10-element Vector{Int64}:
 3
 3
 0
 1
 0
 3
 3
 0
 1
 0

We often need to build matrices of all ones or all zeros.  We use `ones` and `zeros` for this purpose.

In [7]:
B = [ zeros(3,2) ones(3,1) ]

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  1.0
 0.0  0.0  1.0

A single quote `'` after a matrix returns its adjoint.  For real matrices, this is the transpose; for complex-valued matrices, the elements are also conjugated -- this is called the \emph{conjugate transpose} or \emph{Hermitian transpose}.

In [8]:
A'

5×3 adjoint(::Matrix{Float64}) with eltype Float64:
 1.0  50.0  3.14159
 2.0  40.0  1.41421
 3.0  30.0  2.71828
 4.0  20.0  1.61803
 5.0  10.0  1.09861

In [9]:
x'

1×5 adjoint(::Vector{Int64}) with eltype Int64:
 3  3  0  1  0

There are useful shortcuts to build vectors and matrices:

In [10]:
y = 1:4

1:4

In [11]:
z = 0:3:12

0:3:12

In [12]:
s = range(-1,1,length=5)

-1.0:0.5:1.0