# Lecture 3 Playground

Run the included code blocks, understand the output, and note any questions you have!

Square brackets are used to enclose elements of a vector or matrix. Use spaces for horizontal concatenation and semicolons or newlines for vertical concatenation.

In [1]:
A = [ 1 2 3 4 5; 50 40 30 20 10
π sqrt(2) exp(1) (1+sqrt(5))/2 log(3) ]

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

The `size` function gives us the dimensions of an input array.

In [2]:
m,n = size(A)

(3, 5)

A vector is slightly different than a matrix.  A matrix has two dimensions, but a vector has only one dimension.  

In [3]:
x = [ 3, 3, 0, 1, 0 ]
size(x)

(5,)

As long as all blocks are size-compatible, we can build block matrices from vectors and matrices in Julia!

In [4]:
[ x x ]

5×2 Matrix{Int64}:
 3  3
 3  3
 0  0
 1  1
 0  0

In [5]:
[ x; x ]

10-element Vector{Int64}:
 3
 3
 0
 1
 0
 3
 3
 0
 1
 0

We often need to build matrices of all ones or all zeros.  We use `ones` and `zeros` for this purpose.

In [6]:
B = [ zeros(3,2) ones(3,1) ]

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  1.0
 0.0  0.0  1.0

A single quote `'` after a matrix returns its adjoint.  For real matrices, this is the transpose; for complex-valued matrices, the elements are also conjugated -- this is called the \emph{conjugate transpose} or \emph{Hermitian transpose}.

In [7]:
A'

5×3 adjoint(::Matrix{Float64}) with eltype Float64:
 1.0  50.0  3.14159
 2.0  40.0  1.41421
 3.0  30.0  2.71828
 4.0  20.0  1.61803
 5.0  10.0  1.09861

In [8]:
x'

1×5 adjoint(::Vector{Int64}) with eltype Int64:
 3  3  0  1  0

There are useful shortcuts to build vectors and matrices:

In [9]:
y = 1:4

1:4

In [10]:
z = 0:3:12

0:3:12

In [11]:
s = range(-1,1,length=5)

-1.0:0.5:1.0

To access an entry or entries of a vector or matrix, we use brackets and input the desired index or indices.  

In [12]:
a = A[2,end-1]

20.0

In [13]:
x[2]

3

In [14]:
A[1:2,end-2:end]

2×3 Matrix{Float64}:
  3.0   4.0   5.0
 30.0  20.0  10.0

If we enter `:` for any dimension input, it takes all of the indices of that dimension.

In [15]:
A[:, 1:2:end]

3×3 Matrix{Float64}:
  1.0       3.0       5.0
 50.0      30.0      10.0
  3.14159   2.71828   1.09861

All of the usual matrix and vector operations (addition, subtraction, scalar multiplication, multiplication), when defined, are handled by the usual symbols.

In [18]:
display(x - x)
display(2A)
display(A + A)
display(A'*A)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

3×5 Matrix{Float64}:
   2.0       4.0       6.0       8.0      10.0
 100.0      80.0      60.0      40.0      20.0
   6.28319   2.82843   5.43656   3.23607   2.19722

3×5 Matrix{Float64}:
   2.0       4.0       6.0       8.0      10.0
 100.0      80.0      60.0      40.0      20.0
   6.28319   2.82843   5.43656   3.23607   2.19722

5×5 Matrix{Float64}:
 2510.87   2006.44   1511.54   1009.08   508.451
 2006.44   1606.0    1209.84    810.288  411.554
 1511.54   1209.84    916.389   616.398  317.986
 1009.08    810.288   616.398   418.618  221.778
  508.451   411.554   317.986   221.778  126.207

Another really useful operation builds diagonal matrices given an input vector of the entries for the diagonal -- `diagm`.  This function is part of the standard Julia package `LinearAlgebra`.

In [20]:
using LinearAlgebra

B = diagm( [-1,0,-5] )

3×3 Matrix{Int64}:
 -1  0   0
  0  0   0
  0  0  -5